server:
  port: 8081
spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/dabenxiong?serverTimezone=GMT
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.dabenxiong.item.pojo